# Generated by Django 3.2.6 on 2021-08-25 02:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('name_reading', models.CharField(blank=True, max_length=50, null=True, verbose_name='name reading')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal_code')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('number_of', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,14}$')], verbose_name='mobile number')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_employee', to='api.employee')),
            ],
            options={
                'verbose_name_plural': '部署',
                'ordering': ['-created_at'],
            },
        ),
    ]
