# Generated by Django 3.2.6 on 2021-08-31 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,14}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='mobile number'),
        ),
    ]
